<?php
class defaults {
	private $welcome = [
	    "Welcome",
	    "Bienvenue",
	    "Bienvenido",
	    "Willkommen",
	    "Benvenuto",
	    "Bem-vindo",
	    "Welkom",
	    "Добро пожаловать",
	    "欢迎",
	    "歡迎",
	    "ようこそ",
	    "환영합니다",
	    "أهلاً وسهلاً",
	    "स्वागत है",
	    "স্বাগতম",
	    "خوش آمدید",
	    "Hoş geldiniz",
	    "Καλώς ήρθατε",
	    "Witamy",
	    "Vítejte",
	    "Välkommen",
	    "Velkommen",
	    "Tervetuloa",
	    "Velkommen",
	    "Üdvözöljük",
	    "Bine ați venit",
	    "Добре дошли",
	    "Добродошли",
	    "Dobrodošli",
	    "Vitajte",
	    "Dobrodošli",
	    "ברוך הבא",
	    "ยินดีต้อนรับ",
	    "Chào mừng",
	    "Selamat datang",
	    "Selamat datang",
	    "Maligayang pagdating",
	    "Karibu",
	    "Welkom",
	    "خوش آمدید",
	    "ښه راغلاست",
	    "እንኳን ደህና መጡ",
	    "Barka da zuwa",
	    "Wamukelekile",
	    "Wamkelekile",
	    "Kaabo",
	    "Nnọọ",
	    "வரவேற்கிறேன்",
	    "స్వాగతం",
	    "ಸ್ವಾಗತ",
	    "સ્વાગત છે",
	    "ਜੀ ਆਇਆਂ ਨੂੰ",
	    "स्वागत छ",
	    "ကြိုဆိုပါတယ်",
	    "សូមស្វាគមន៍",
	    "ຍິນດີຕ້ອນຮັບ",
	    "Тавтай морилно уу",
	    "Ласкаво просимо",
	    "Сардэчна запрашаем",
	    "Sveiki atvykę",
	    "Laipni lūdzam",
	    "Tere tulemast",
	    "Velkomin",
	    "Fáilte",
	    "Croeso",
	    "Ongi etorri",
	    "Benvingut",
	    "Benvido",
	    "Byenveni",
	    "Bonvenon",
	    "Nau mai",
	    "Afio mai",
	    "Mālō e lava mai",
	    "Aloha",
	    "Wëllkomm",
	    "Merħba",
	    "Mirë se vini",
	    "Dobrodošli",
	    "Добредојдовте",
	    "მოგესალმებით",
	    "Բարի գալուստ",
	    "Қош келдіңіз",
	    "Xush kelibsiz",
	    "Кош келиңиз",
	    "Хуш омадед",
	    "Hoş geldiňiz",
	    "Xoş gəlmisiniz",
	    "സ്വാഗതം",
	    "ආයුබෝවන්",
	    "स्वागत आहे"
	];

	public function getWelcomes() { return $this->welcome; }
	public function getWallpapers() {
		$r = rand(1, 6);
		return "/img/{$r}.jpg";
	}

}